#!/usr/bin/env python
# -*- coding: utf-8 -*-

import argparse
import subprocess


def create_parser():
    parser = argparse.ArgumentParser(description='Miller Space Mapper run script for use with ParProcCo')
    parser.add_argument('--input_path', help='str: input data file', required=True)
    parser.add_argument('--output_path', help='str: output file path', required=True)
    parser.add_argument('-I', help='str: image slice parameter', required=True)
    parser.add_argument('-s', '--step', help='float: step', default=0.01)
    parser.add_argument('-c', '--cpu', help='int: cpus', default=None)
    parser.add_argument('-t', '--timeout', help='int: timeout (in minutes)', default=None)
    return parser


def run_rs_map(args):
    script_args = ["rs_map", "-o", args.output_path, "-I", args.I, "-s", str(args.step), args.input_path]
    proc = subprocess.Popen(script_args)
    proc.communicate()
    print("complete")


if __name__ == '__main__':
    args = create_parser().parse_args()
    print(f"Parsing {args}")
    run_rs_map(args)
