#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from __future__ import annotations

import argparse
from pathlib import Path

from ParProcCo.msmapper_aggregator import MSMAggregator


def create_parser():
    '''
     $ msm_agg_jobscript --output output_file input files ...
     '''
    parser = argparse.ArgumentParser(description='Miller Space Mapper run script for use with ParProcCo')
    parser.add_argument('--output', help='str: output file', required=True)
    parser.add_argument("sliced_files", help="str: paths to sliced result files", type=str, nargs="+")

    return parser


def run_aggregator(args: argparse.Namespace) -> None:
    '''
    Run MSMAggregator
    '''
    args.output = Path(args.output)
    sliced_file_paths = [Path(x) for x in args.sliced_files]

    MSMAggregator().aggregate(args.output, sliced_file_paths)


if __name__ == '__main__':
    args, other_args = create_parser().parse_known_args()
    run_aggregator(args)
