#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from __future__ import annotations

import argparse
import subprocess

from ParProcCo.utils import check_location, get_absolute_path


def create_parser():
    parser = argparse.ArgumentParser(description='Miller Space Mapper run script for use with ParProcCo')
    parser.add_argument('--output_path', help='str: output file path', required=True)
    parser.add_argument('-I', help='str: image slice parameter', required=True)
    return parser


def run_rs_map(args, script_args):
    print("run_rs_map args are: ", args)
    print("run_rs_map script_args are: ", script_args)
    script = check_location(get_absolute_path(script_args[0]))
    jobscript = script_args[0]

    rs_map_args = [jobscript, "-o", args.output_path, "-I", args.I] + script_args[1:]
    print("rs_map_args are: ", rs_map_args)
    print("script is: ", script)
    print("jobscript is: ", jobscript)

    proc = subprocess.Popen(rs_map_args)
    proc.communicate()
    print("complete")


if __name__ == '__main__':
    args, script_args = create_parser().parse_known_args()
    print(f"Parsing {args} and {script_args}")
    run_rs_map(args, script_args)
